language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "4"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libicu-dev
      - gcc-4.8
      - g++-4.8
before_install:
  - npm install -g npm
